services:
  - type: web
    name: byukiva-api
    env: docker
    plan: free
    region: ohio
    buildCommand: dotnet publish -c Release
    startCommand: dotnet Integrity.API/bin/Release/net8.0/Integrity.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: byukiva-db
          property: connectionString
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: byukiva-db
          property: connectionString
      - key: Jwt__Key
        generateValue: true

databases:
  - name: byukiva-db
    plan: free
    region: ohio
    ipAllowList: [] 