services:
  - type: web
    name: byukiva-api
    env: docker
    plan: free
    region: oregon
    buildCommand: dotnet publish -c Release
    startCommand: dotnet Integrity.API/bin/Release/net8.0/Integrity.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: humanconnectionproject
          property: connectionString
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: humanconnectionproject
          property: connectionString
      - key: Jwt__Key
        generateValue: true

databases:
  - name: humanconnectionproject
    plan: free
    region: oregon
    ipAllowList: [] 