services:
  - type: web
    name: byukiva-api
    env: docker
    plan: free
    region: oregon
    buildCommand: dotnet publish -c Release
    startCommand: dotnet Integrity.API/bin/Release/net8.0/Integrity.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Key
        generateValue: true 