services:
  - type: web
    name: byukiva-api
    env: docker
    plan: free
    region: oregon
    buildCommand: dotnet publish -c Release
    startCommand: dotnet Integrity.API/bin/Release/net8.0/Integrity.API.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: postgresql://humanconnectionproject_db_user:gblAYBWdBUVHQLhi9xuC5YknLmWvqjMS@dpg-d1rs9d6r433s73anj550-a:5432/humanconnectionproject_db
      - key: ConnectionStrings__DefaultConnection
        value: postgresql://humanconnectionproject_db_user:gblAYBWdBUVHQLhi9xuC5YknLmWvqjMS@dpg-d1rs9d6r433s73anj550-a:5432/humanconnectionproject_db
      - key: Jwt__Key
        generateValue: true 